pipeline{
    agent any
    tools{
        go 'go-1.13.6'
    }
    environment {
        GO111MODULE = 'on'
    }
    stages {
        stage('Compile') {
            steps {
                sh 'go version'
            }
        }
    }
//Compile
//Tests
//Code quality
//Release


}
