version: '3.8'

services:
  library-db:
    image: postgres:15
    container_name: library-db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/library_schema.sql:/docker-entrypoint-initdb.d/library_schema.sql
    networks:
      - library-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d library"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    networks:
      - library-network
    depends_on:
      - library-db

  # Datadog Agent for log collection and monitoring
  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    container_name: datadog-agent
    environment:
      # Replace 'your-api-key-here' with your actual Datadog API key
      - DD_API_KEY=${DD_API_KEY:-your-api-key-here}
      - DD_SITE=${DD_SITE:-datadoghq.com}
      - DD_HOSTNAME=book-search-app
      - DD_ENV=${DD_ENV:-development}
      - DD_SERVICE=book-search
      - DD_VERSION=${DD_VERSION:-1.0.0}
      # Enable log collection
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      # Enable APM (Application Performance Monitoring)
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      # Enable container monitoring
      - DD_CONTAINER_EXCLUDE_LOGS="name:datadog-agent"
      # Docker integration
      - DD_DOCKER_LABELS_AS_TAGS='{"*":"%%label%%"}'
      - DD_DOCKER_ENV_AS_TAGS='{"*":"%%env%%"}'
    volumes:
      # Mount Docker socket for container discovery
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount proc and cgroup for system metrics
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      # Log collection from containers
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      # Optional: Mount config directory
      - ./datadog-config:/etc/datadog-agent/conf.d:ro
    networks:
      - library-network
    ports:
      # APM traces
      - "8126:8126"
      # DogStatsD metrics
      - "8125:8125/udp"
    restart: unless-stopped
    labels:
      - "com.datadoghq.ad.logs=[{\"source\":\"datadog-agent\",\"service\":\"datadog-agent\"}]"

  # data-importer:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.init
  #   container_name: data-importer
  #   networks:
  #     - library-network
  #   depends_on:
  #     library-db:
  #       condition: service_healthy
  #   environment:
  #     - DB_URL=jdbc:postgresql://library-db:5432/library
  #     - DB_USER=admin
  #     - DB_PASSWORD=admin
  #     - CSV_PATH=/app/resources/books.csv
  #   restart: "no"

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge
