version: '3.8'

services:
  library-db:
    image: postgres:15
    container_name: library-db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/library_schema.sql:/docker-entrypoint-initdb.d/library_schema.sql
    networks:
      - library-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d library"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    networks:
      - library-network
    depends_on:
      - library-db

  # data-importer:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.init
  #   container_name: data-importer
  #   networks:
  #     - library-network
  #   depends_on:
  #     library-db:
  #       condition: service_healthy
  #   environment:
  #     - DB_URL=jdbc:postgresql://library-db:5432/library
  #     - DB_USER=admin
  #     - DB_PASSWORD=admin
  #     - CSV_PATH=/app/resources/books.csv
  #   restart: "no"

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge
