---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-service
  namespace: development
  labels:
    app: busybox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-deployment
  template:
    metadata:
      labels:
        app: busybox-deployment
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["sleep", "3600"]
        env: 
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
