[project]
name = "practice"
version = "0.1.0"
description = "practice project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

[tool.pytest.ini_options]
pythonpath = ["ws-python/practice/src"]